name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and Push Dash Dashboard
      uses: docker/build-push-action@v5
      with:
        context: ./dashboard/06_Dashboard
        push: true
        tags: ghcr.io/razerardi/credit-card-fraud-ml/risk-dashboard:latest

    - name: Build and Push FastAPI Serving
      uses: docker/build-push-action@v5
      with:
        context: ./dashboard/05_Model_Serving
        push: true
        tags: ghcr.io/razerardi/credit-card-fraud-ml/risk-dashboard-api:latest